### ISSUE TITLE
Any way to do commandline?

### ISSUE THREAD

**Issue by concifederico** [andrewhodel/gcode-optimizer#2]
Hi! Love this project. Very straight and useful. The point is I would like to automate it by a commandline interface. I'm a Python programmer, 0% Web Java.
Any idea will be fully appreciated!
Regards!

Federico

**Comment by andrewhodel** [comment]
First you would install the interpreted language you love the most.

Well, maybe you would need to install it but maybe there's no routine to check it.

Then after that you would do the same thing in your language.

It might be somewhat similar, if it does nothing but take known inputs and output known outputs.

Then when you are programming for the rest of time, and there's one inconsistency you can always be there to fix it.

Sound good?

**Comment by concifederico** [comment]
No, it sounds quite bad.. That means there is no way to call it like a module from the outside? I just want to connect gcodetools to your optimizer like theoptimizer -i input.g -o output.g -w 1 (wait for the best iteration in 1 minute. Do you mean I should develop the algorithm in python from zero?
